name: generate snake

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: generate github contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=#2C4768&color_dots=#fdfcf7,#dbe5f1,#94b0d6,#5878a8,#2C4768
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#fdfcf7&color_dots=#1a2a40,#23344f,#3a5a8a,#7a99c4,#fdfcf7

      - name: push generated svg to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
